// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `ssd-git.juniper.net_contrail_cn2_third_party_apiserver-builder-alpha_pkg_builders_generated.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

static file_descriptor_proto_data: &'static [u8] = b"\
    \nassd-git.juniper.net_contrail_cn2_third_party_apiserver-builder-alpha_\
    pkg_builders_generated.proto\x120sigs.k8s.io.apiserver_builder_alpha.pkg\
    .buildersJ0\n\x06\x12\x04\0\0\x039\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x1c\
    \n\x01\x02\x12\x03\x03\x088\x1a\x12\x20Dummy\x20proto\x20file\n\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
